port: "8181"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "ha_db"
  sslmode: "disable"
  password: "amirroot"

base_url: "http://192.168.100.54:8181/"

logger:
  filename: "logs/foo.log"
  max_size: "10"
  max_backups: "3"
  max_age: "28"
  compress: "true"
  